// Catálogo fijo de permisos del sistema. Fuente de verdad: este archivo.
// Los seeds SQL son una pre-carga; el `PermissionsSyncService` ejecuta
// UPSERT al arranque para mantener BD ↔ código sincronizados.
//
// Convención del code: `modulo.recurso.accion`. is_sensitive=true marca
// permisos cuya invocación se audita como lectura sensible (ADR-B-009).
//
// Reglas:
//   1. Agregar permisos solo aquí (no en seeds nuevos). El seed inicial
//      `database/seed/02_permissions.sql` puede quedar desactualizado;
//      este catálogo lo reconcilia al arranque.
//   2. NUNCA renombrar un `code` — los `role_permissions` lo referencian.
//      Si hay que cambiar, agregar el nuevo + mantener el viejo + migrar.
//   3. NUNCA borrar un `code` sin verificar que ningún `role_permissions`
//      lo use (el FK no permite borrar pero el catálogo se marcaría
//      inconsistente).

export interface PermissionDefinition {
  readonly code: string;
  readonly module: string;
  readonly resource: string;
  readonly action: string;
  readonly description: string;
  readonly isSensitive: boolean;
}

export const PERMISSIONS_CATALOG: readonly PermissionDefinition[] = [
  // audit
  {
    code: 'audit.logs.read',
    module: 'audit',
    resource: 'logs',
    action: 'read',
    description: 'Leer audit logs',
    isSensitive: true,
  },

  // blocks
  {
    code: 'blocks.blocks.grant',
    module: 'blocks',
    resource: 'blocks',
    action: 'grant',
    description: 'Crear bloqueo',
    isSensitive: false,
  },
  {
    code: 'blocks.blocks.read',
    module: 'blocks',
    resource: 'blocks',
    action: 'read',
    description: 'Leer bloqueos',
    isSensitive: false,
  },
  {
    code: 'blocks.blocks.revoke',
    module: 'blocks',
    resource: 'blocks',
    action: 'revoke',
    description: 'Levantar bloqueo',
    isSensitive: false,
  },

  // cases (causas judiciales — solo organization principal)
  {
    code: 'cases.appeals.create',
    module: 'cases',
    resource: 'appeals',
    action: 'create',
    description: 'Presentar recursos',
    isSensitive: false,
  },
  {
    code: 'cases.appeals.read',
    module: 'cases',
    resource: 'appeals',
    action: 'read',
    description: 'Leer recursos',
    isSensitive: true,
  },
  {
    code: 'cases.cases.assign_lawyer',
    module: 'cases',
    resource: 'cases',
    action: 'assign_lawyer',
    description: 'Asignar abogado a causa',
    isSensitive: true,
  },
  {
    code: 'cases.cases.create',
    module: 'cases',
    resource: 'cases',
    action: 'create',
    description: 'Iniciar causa (presentar querella)',
    isSensitive: false,
  },
  {
    code: 'cases.cases.read',
    module: 'cases',
    resource: 'cases',
    action: 'read',
    description: 'Leer causas',
    isSensitive: true,
  },
  {
    code: 'cases.cases.reopen',
    module: 'cases',
    resource: 'cases',
    action: 'reopen',
    description: 'Reabrir causa cerrada',
    isSensitive: true,
  },
  {
    code: 'cases.cases.update',
    module: 'cases',
    resource: 'cases',
    action: 'update',
    description: 'Actualizar causa',
    isSensitive: false,
  },
  {
    code: 'cases.deadlines.read',
    module: 'cases',
    resource: 'deadlines',
    action: 'read',
    description: 'Leer plazos de causa',
    isSensitive: false,
  },
  {
    code: 'cases.deadlines.waive',
    module: 'cases',
    resource: 'deadlines',
    action: 'waive',
    description: 'Descartar plazos con razón (solo Abogado Admin)',
    isSensitive: true,
  },
  {
    code: 'cases.documents.download',
    module: 'cases',
    resource: 'documents',
    action: 'download',
    description: 'Descargar documentos (auditado)',
    isSensitive: true,
  },
  {
    code: 'cases.documents.upload',
    module: 'cases',
    resource: 'documents',
    action: 'upload',
    description: 'Subir documentos / nuevas versiones',
    isSensitive: false,
  },
  {
    code: 'cases.hearings.manage',
    module: 'cases',
    resource: 'hearings',
    action: 'manage',
    description: 'Crear/editar audiencias y registrar resultados',
    isSensitive: false,
  },
  {
    code: 'cases.hearings.read',
    module: 'cases',
    resource: 'hearings',
    action: 'read',
    description: 'Leer audiencias',
    isSensitive: false,
  },
  {
    code: 'cases.milestones.create',
    module: 'cases',
    resource: 'milestones',
    action: 'create',
    description: 'Registrar hitos procesales',
    isSensitive: false,
  },
  {
    code: 'cases.milestones.read',
    module: 'cases',
    resource: 'milestones',
    action: 'read',
    description: 'Leer hitos procesales',
    isSensitive: true,
  },
  {
    code: 'cases.notes.manage',
    module: 'cases',
    resource: 'notes',
    action: 'manage',
    description: 'Crear/editar notas propias',
    isSensitive: false,
  },
  {
    code: 'cases.notes.read_private',
    module: 'cases',
    resource: 'notes',
    action: 'read_private',
    description: 'Leer notas privadas (solo equipo asignado)',
    isSensitive: true,
  },
  {
    code: 'cases.querellas.create',
    module: 'cases',
    resource: 'querellas',
    action: 'create',
    description: 'Presentar querellas',
    isSensitive: false,
  },
  {
    code: 'cases.querellas.read',
    module: 'cases',
    resource: 'querellas',
    action: 'read',
    description: 'Leer querellas presentadas',
    isSensitive: false,
  },
  {
    code: 'cases.resolutions.create',
    module: 'cases',
    resource: 'resolutions',
    action: 'create',
    description: 'Registrar resoluciones',
    isSensitive: false,
  },
  {
    code: 'cases.resolutions.read',
    module: 'cases',
    resource: 'resolutions',
    action: 'read',
    description: 'Leer resoluciones del tribunal',
    isSensitive: true,
  },
  {
    code: 'cases.tasks.assign',
    module: 'cases',
    resource: 'tasks',
    action: 'assign',
    description: 'Asignar tareas a otros',
    isSensitive: false,
  },
  {
    code: 'cases.tasks.complete',
    module: 'cases',
    resource: 'tasks',
    action: 'complete',
    description: 'Completar tareas asignadas',
    isSensitive: false,
  },
  {
    code: 'cases.tasks.create',
    module: 'cases',
    resource: 'tasks',
    action: 'create',
    description: 'Crear tareas',
    isSensitive: false,
  },
  {
    code: 'cases.templates.manage',
    module: 'cases',
    resource: 'templates',
    action: 'manage',
    description: 'Editar plantillas de escritos (solo Abogado Admin)',
    isSensitive: false,
  },

  // catalog
  {
    code: 'catalog.catalog.manage',
    module: 'catalog',
    resource: 'catalog',
    action: 'manage',
    description: 'Editar catálogos del sistema',
    isSensitive: false,
  },
  {
    code: 'catalog.geometries.import',
    module: 'catalog',
    resource: 'geometries',
    action: 'import',
    description: 'Importar KMZ de zonas/áreas/predios',
    isSensitive: true,
  },

  // complaints (denuncias)
  {
    code: 'complaints.complaints.create',
    module: 'complaints',
    resource: 'complaints',
    action: 'create',
    description: 'Presentar denuncias',
    isSensitive: false,
  },
  {
    code: 'complaints.complaints.read',
    module: 'complaints',
    resource: 'complaints',
    action: 'read',
    description: 'Leer denuncias',
    isSensitive: false,
  },
  {
    code: 'complaints.complaints.update',
    module: 'complaints',
    resource: 'complaints',
    action: 'update',
    description: 'Actualizar denuncias',
    isSensitive: false,
  },
  {
    code: 'complaints.persons.manage',
    module: 'complaints',
    resource: 'persons',
    action: 'manage',
    description: 'Vincular personas (imputados/testigos/denunciante) a denuncia',
    isSensitive: false,
  },
  {
    code: 'complaints.vehicles.manage',
    module: 'complaints',
    resource: 'vehicles',
    action: 'manage',
    description: 'Vincular vehículos a denuncia (incautación / devolución)',
    isSensitive: false,
  },

  // fires
  {
    code: 'fires.documents.delete',
    module: 'fires',
    resource: 'documents',
    action: 'delete',
    description: 'Marcar documento como eliminado (soft delete)',
    isSensitive: true,
  },
  {
    code: 'fires.documents.download',
    module: 'fires',
    resource: 'documents',
    action: 'download',
    description: 'Descargar documento (acción auditada)',
    isSensitive: true,
  },
  {
    code: 'fires.documents.read',
    module: 'fires',
    resource: 'documents',
    action: 'read',
    description: 'Leer metadata de documentos',
    isSensitive: false,
  },
  {
    code: 'fires.documents.update',
    module: 'fires',
    resource: 'documents',
    action: 'update',
    description: 'Actualizar metadata del documento',
    isSensitive: false,
  },
  {
    code: 'fires.documents.upload',
    module: 'fires',
    resource: 'documents',
    action: 'upload',
    description: 'Subir reporte CONAF / Bomberos / pericia',
    isSensitive: false,
  },
  {
    code: 'fires.fires.close',
    module: 'fires',
    resource: 'fires',
    action: 'close',
    description: 'Cerrar incendio administrativamente',
    isSensitive: false,
  },
  {
    code: 'fires.fires.create',
    module: 'fires',
    resource: 'fires',
    action: 'create',
    description: 'Reportar nuevo incendio detectado',
    isSensitive: false,
  },
  {
    code: 'fires.fires.determine_origin',
    module: 'fires',
    resource: 'fires',
    action: 'determine_origin',
    description:
      'Determinar causa de origen tras pericia (intencional/negligente/eléctrica/natural)',
    isSensitive: true,
  },
  {
    code: 'fires.fires.file_conaf_complaint',
    module: 'fires',
    resource: 'fires',
    action: 'file_conaf_complaint',
    description: 'Registrar denuncia/sanción CONAF',
    isSensitive: false,
  },
  {
    code: 'fires.fires.flag_terrorism',
    module: 'fires',
    resource: 'fires',
    action: 'flag_terrorism',
    description: 'Marcar/desmarcar flag de atentado incendiario',
    isSensitive: true,
  },
  {
    code: 'fires.fires.link_case',
    module: 'fires',
    resource: 'fires',
    action: 'link_case',
    description: 'Vincular incendio con una causa penal',
    isSensitive: false,
  },
  {
    code: 'fires.fires.link_incident',
    module: 'fires',
    resource: 'fires',
    action: 'link_incident',
    description: 'Vincular incendio con un incident formal',
    isSensitive: false,
  },
  {
    code: 'fires.fires.qualify_legally',
    module: 'fires',
    resource: 'fires',
    action: 'qualify_legally',
    description: 'Asignar calificación legal (CP 476 N°3, art. 490, etc.)',
    isSensitive: true,
  },
  {
    code: 'fires.fires.read',
    module: 'fires',
    resource: 'fires',
    action: 'read',
    description: 'Leer registros de incendios',
    isSensitive: false,
  },
  {
    code: 'fires.fires.transition_state',
    module: 'fires',
    resource: 'fires',
    action: 'transition_state',
    description: 'Avanzar estado del combate (despachado→arribado→controlado→extinguido)',
    isSensitive: false,
  },
  {
    code: 'fires.fires.update',
    module: 'fires',
    resource: 'fires',
    action: 'update',
    description: 'Actualizar metadata operativa (tiempos combate, recursos)',
    isSensitive: false,
  },
  {
    code: 'fires.fires.void',
    module: 'fires',
    resource: 'fires',
    action: 'void',
    description: 'Anular registro de incendio (falsa alarma)',
    isSensitive: true,
  },

  // incidents
  {
    code: 'incidents.evidence.download',
    module: 'incidents',
    resource: 'evidence',
    action: 'download',
    description: 'Descargar evidencia (auditado)',
    isSensitive: true,
  },
  {
    code: 'incidents.evidence.upload',
    module: 'incidents',
    resource: 'evidence',
    action: 'upload',
    description: 'Subir evidencia',
    isSensitive: false,
  },
  {
    code: 'incidents.incidents.close',
    module: 'incidents',
    resource: 'incidents',
    action: 'close',
    description: 'Cerrar incidentes',
    isSensitive: false,
  },
  {
    code: 'incidents.incidents.create',
    module: 'incidents',
    resource: 'incidents',
    action: 'create',
    description: 'Crear incidentes',
    isSensitive: false,
  },
  {
    code: 'incidents.incidents.read',
    module: 'incidents',
    resource: 'incidents',
    action: 'read',
    description: 'Leer incidentes',
    isSensitive: false,
  },
  {
    code: 'incidents.incidents.set_semaforo',
    module: 'incidents',
    resource: 'incidents',
    action: 'set_semaforo',
    description: 'Modificar semáforo URP',
    isSensitive: false,
  },
  {
    code: 'incidents.incidents.update',
    module: 'incidents',
    resource: 'incidents',
    action: 'update',
    description: 'Actualizar incidentes (informe URP)',
    isSensitive: false,
  },
  {
    code: 'incidents.incidents.void',
    module: 'incidents',
    resource: 'incidents',
    action: 'void',
    description: 'Anular incidentes (mantiene correlativo)',
    isSensitive: false,
  },

  // maat
  {
    code: 'maat.records.manage',
    module: 'maat',
    resource: 'records',
    action: 'manage',
    description: 'Gestionar registros MAAT',
    isSensitive: true,
  },
  {
    code: 'maat.records.read',
    module: 'maat',
    resource: 'records',
    action: 'read',
    description: 'Leer registros MAAT',
    isSensitive: true,
  },

  // organizations
  {
    code: 'organizations.organizations.manage',
    module: 'organizations',
    resource: 'organizations',
    action: 'manage',
    description: 'Gestionar organizaciones',
    isSensitive: true,
  },
  {
    code: 'organizations.zones.assign',
    module: 'organizations',
    resource: 'zones',
    action: 'assign',
    description: 'Reasignar zonas a empresas de seguridad',
    isSensitive: true,
  },

  // persons
  {
    code: 'persons.addresses.create',
    module: 'persons',
    resource: 'addresses',
    action: 'create',
    description: 'Registrar nueva dirección del party',
    isSensitive: false,
  },
  {
    code: 'persons.addresses.expire',
    module: 'persons',
    resource: 'addresses',
    action: 'expire',
    description: 'Marcar dirección como vencida (valid_to)',
    isSensitive: false,
  },
  {
    code: 'persons.addresses.read',
    module: 'persons',
    resource: 'addresses',
    action: 'read',
    description: 'Leer direcciones del party',
    isSensitive: true,
  },
  {
    code: 'persons.addresses.update',
    module: 'persons',
    resource: 'addresses',
    action: 'update',
    description: 'Actualizar dirección (vigencia, notas, confidence)',
    isSensitive: false,
  },
  {
    code: 'persons.aliases.create',
    module: 'persons',
    resource: 'aliases',
    action: 'create',
    description: 'Registrar nuevo alias',
    isSensitive: false,
  },
  {
    code: 'persons.aliases.deactivate',
    module: 'persons',
    resource: 'aliases',
    action: 'deactivate',
    description: 'Desactivar alias (active=false)',
    isSensitive: false,
  },
  {
    code: 'persons.aliases.read',
    module: 'persons',
    resource: 'aliases',
    action: 'read',
    description: 'Leer aliases del party',
    isSensitive: true,
  },
  {
    code: 'persons.aliases.update',
    module: 'persons',
    resource: 'aliases',
    action: 'update',
    description: 'Actualizar alias (last_seen, confidence, notas)',
    isSensitive: false,
  },
  {
    code: 'persons.band_memberships.assign',
    module: 'persons',
    resource: 'band_memberships',
    action: 'assign',
    description: 'Asignar party a banda',
    isSensitive: false,
  },
  {
    code: 'persons.band_memberships.end',
    module: 'persons',
    resource: 'band_memberships',
    action: 'end',
    description: 'Cerrar membresía (active=false + ended_at)',
    isSensitive: false,
  },
  {
    code: 'persons.band_memberships.read',
    module: 'persons',
    resource: 'band_memberships',
    action: 'read',
    description: 'Leer membresías party↔band',
    isSensitive: true,
  },
  {
    code: 'persons.band_memberships.update',
    module: 'persons',
    resource: 'band_memberships',
    action: 'update',
    description: 'Actualizar membresía (rol, last_observed, confidence)',
    isSensitive: false,
  },
  {
    code: 'persons.bands.create',
    module: 'persons',
    resource: 'bands',
    action: 'create',
    description: 'Crear nueva banda en el catálogo',
    isSensitive: false,
  },
  {
    code: 'persons.bands.deactivate',
    module: 'persons',
    resource: 'bands',
    action: 'deactivate',
    description: 'Desactivar banda',
    isSensitive: false,
  },
  {
    code: 'persons.bands.read',
    module: 'persons',
    resource: 'bands',
    action: 'read',
    description: 'Leer catálogo de bandas',
    isSensitive: false,
  },
  {
    code: 'persons.bands.read_internal',
    module: 'persons',
    resource: 'bands',
    action: 'read_internal',
    description: 'Leer notas internas operativas URP de la banda',
    isSensitive: true,
  },
  {
    code: 'persons.bands.update',
    module: 'persons',
    resource: 'bands',
    action: 'update',
    description: 'Actualizar banda (descripción, área operativa, notas)',
    isSensitive: false,
  },
  {
    code: 'persons.documents.delete',
    module: 'persons',
    resource: 'documents',
    action: 'delete',
    description: 'Marcar documento como eliminado (soft delete)',
    isSensitive: true,
  },
  {
    code: 'persons.documents.download',
    module: 'persons',
    resource: 'documents',
    action: 'download',
    description: 'Descargar documento (acción auditada)',
    isSensitive: true,
  },
  {
    code: 'persons.documents.read',
    module: 'persons',
    resource: 'documents',
    action: 'read',
    description: 'Leer metadata de documentos del party',
    isSensitive: true,
  },
  {
    code: 'persons.documents.update',
    module: 'persons',
    resource: 'documents',
    action: 'update',
    description: 'Actualizar metadata del documento (no contenido)',
    isSensitive: false,
  },
  {
    code: 'persons.documents.upload',
    module: 'persons',
    resource: 'documents',
    action: 'upload',
    description: 'Subir nuevo documento al party',
    isSensitive: false,
  },
  {
    code: 'persons.imputados.read',
    module: 'persons',
    resource: 'imputados',
    action: 'read',
    description: 'Leer datos de imputados (sensible)',
    isSensitive: true,
  },
  {
    code: 'persons.persons.create',
    module: 'persons',
    resource: 'persons',
    action: 'create',
    description: 'Crear personas',
    isSensitive: false,
  },
  {
    code: 'persons.persons.merge',
    module: 'persons',
    resource: 'persons',
    action: 'merge',
    description: 'Fusionar duplicados (solo Administrador)',
    isSensitive: true,
  },
  {
    code: 'persons.persons.read',
    module: 'persons',
    resource: 'persons',
    action: 'read',
    description: 'Leer personas',
    isSensitive: false,
  },
  {
    code: 'persons.persons.update',
    module: 'persons',
    resource: 'persons',
    action: 'update',
    description: 'Actualizar personas',
    isSensitive: false,
  },

  // police_units
  {
    code: 'police_units.units.normalize',
    module: 'police_units',
    resource: 'units',
    action: 'normalize',
    description: 'Normalizar unidades policiales (Abogado Administrador)',
    isSensitive: true,
  },
  {
    code: 'police_units.units.read',
    module: 'police_units',
    resource: 'units',
    action: 'read',
    description: 'Leer unidades policiales',
    isSensitive: false,
  },

  // queries (API externa de consulta)
  {
    code: 'queries.blocks.check',
    module: 'queries',
    resource: 'blocks',
    action: 'check',
    description: 'Consultar bloqueo de RUT/patente (auditado por consulta)',
    isSensitive: true,
  },

  // reports (informes operativos — UI URP)
  {
    code: 'reports.reports.export',
    module: 'reports',
    resource: 'reports',
    action: 'export',
    description: 'Exportar reportes (Excel/PDF/CSV)',
    isSensitive: true,
  },
  {
    code: 'reports.reports.read',
    module: 'reports',
    resource: 'reports',
    action: 'read',
    description: 'Acceder a reportes',
    isSensitive: false,
  },

  // roles
  {
    code: 'roles.roles.manage',
    module: 'roles',
    resource: 'roles',
    action: 'manage',
    description: 'Gestionar roles',
    isSensitive: true,
  },

  // rules (motor de sugerencias)
  {
    code: 'rules.rules.create',
    module: 'rules',
    resource: 'rules',
    action: 'create',
    description: 'Crear nueva regla',
    isSensitive: false,
  },
  {
    code: 'rules.rules.deactivate',
    module: 'rules',
    resource: 'rules',
    action: 'deactivate',
    description: 'Desactivar regla',
    isSensitive: false,
  },
  {
    code: 'rules.rules.preview',
    module: 'rules',
    resource: 'rules',
    action: 'preview',
    description: 'Simular impacto de regla antes de activar',
    isSensitive: false,
  },
  {
    code: 'rules.rules.read',
    module: 'rules',
    resource: 'rules',
    action: 'read',
    description: 'Leer catálogo de reglas',
    isSensitive: false,
  },
  {
    code: 'rules.rules.update',
    module: 'rules',
    resource: 'rules',
    action: 'update',
    description: 'Editar regla (criteria, mensaje, prioridad, active)',
    isSensitive: false,
  },
  {
    code: 'rules.suggestions.dismiss',
    module: 'rules',
    resource: 'suggestions',
    action: 'dismiss',
    description: 'Descartar sugerencia con motivo',
    isSensitive: false,
  },
  {
    code: 'rules.suggestions.mark_followed',
    module: 'rules',
    resource: 'suggestions',
    action: 'mark_followed',
    description: 'Marcar sugerencia como seguida (escalada o no)',
    isSensitive: false,
  },
  {
    code: 'rules.suggestions.read',
    module: 'rules',
    resource: 'suggestions',
    action: 'read',
    description: 'Leer sugerencias generadas',
    isSensitive: false,
  },

  // statistics (catálogo formal de reportes + ejecuciones + suscripciones)
  {
    code: 'statistics.reports.cancel',
    module: 'statistics',
    resource: 'reports',
    action: 'cancel',
    description: 'Cancelar ejecución en curso',
    isSensitive: false,
  },
  {
    code: 'statistics.reports.download',
    module: 'statistics',
    resource: 'reports',
    action: 'download',
    description: 'Descargar archivo de reporte (acción auditada)',
    isSensitive: true,
  },
  {
    code: 'statistics.reports.execute',
    module: 'statistics',
    resource: 'reports',
    action: 'execute',
    description: 'Ejecutar reporte a demanda',
    isSensitive: false,
  },
  {
    code: 'statistics.reports.execute_audit',
    module: 'statistics',
    resource: 'reports',
    action: 'execute_audit',
    description: 'Ejecutar reportes de auditoría (accesos a datos sensibles)',
    isSensitive: true,
  },
  {
    code: 'statistics.reports.execute_data_protection',
    module: 'statistics',
    resource: 'reports',
    action: 'execute_data_protection',
    description: 'Ejecutar reportes Ley 21.719 (ARCOPOL+, brechas)',
    isSensitive: true,
  },
  {
    code: 'statistics.reports.read',
    module: 'statistics',
    resource: 'reports',
    action: 'read',
    description: 'Leer catálogo de reportes',
    isSensitive: false,
  },
  {
    code: 'statistics.reports.view_results',
    module: 'statistics',
    resource: 'reports',
    action: 'view_results',
    description: 'Ver resultados de ejecuciones (lista + metadata)',
    isSensitive: false,
  },
  {
    code: 'statistics.schedules.create',
    module: 'statistics',
    resource: 'schedules',
    action: 'create',
    description: 'Crear nueva programación',
    isSensitive: false,
  },
  {
    code: 'statistics.schedules.delete',
    module: 'statistics',
    resource: 'schedules',
    action: 'delete',
    description: 'Eliminar programación (soft delete)',
    isSensitive: false,
  },
  {
    code: 'statistics.schedules.read',
    module: 'statistics',
    resource: 'schedules',
    action: 'read',
    description: 'Leer programación de reportes',
    isSensitive: false,
  },
  {
    code: 'statistics.schedules.update',
    module: 'statistics',
    resource: 'schedules',
    action: 'update',
    description: 'Actualizar programación',
    isSensitive: false,
  },
  {
    code: 'statistics.subscriptions.manage_any',
    module: 'statistics',
    resource: 'subscriptions',
    action: 'manage_any',
    description: 'Gestionar suscripciones de cualquier usuario',
    isSensitive: true,
  },
  {
    code: 'statistics.subscriptions.manage_own',
    module: 'statistics',
    resource: 'subscriptions',
    action: 'manage_own',
    description: 'Suscribirse/desuscribirse',
    isSensitive: false,
  },
  {
    code: 'statistics.subscriptions.read_own',
    module: 'statistics',
    resource: 'subscriptions',
    action: 'read_own',
    description: 'Leer mis suscripciones',
    isSensitive: false,
  },

  // surveillance
  {
    code: 'surveillance.audits.close',
    module: 'surveillance',
    resource: 'audits',
    action: 'close',
    description: 'Cerrar auditoría con overall_result (acción irreversible)',
    isSensitive: true,
  },
  {
    code: 'surveillance.audits.create',
    module: 'surveillance',
    resource: 'audits',
    action: 'create',
    description: 'Iniciar nueva auditoría URP a contratista',
    isSensitive: false,
  },
  {
    code: 'surveillance.audits.read',
    module: 'surveillance',
    resource: 'audits',
    action: 'read',
    description: 'Leer auditorías de compliance URP',
    isSensitive: false,
  },
  {
    code: 'surveillance.audits.update',
    module: 'surveillance',
    resource: 'audits',
    action: 'update',
    description: 'Actualizar auditoría en curso (alcance, hallazgos, notas)',
    isSensitive: false,
  },
  {
    code: 'surveillance.certifications.manage',
    module: 'surveillance',
    resource: 'certifications',
    action: 'manage',
    description: 'Crear / actualizar credenciales (OS-10 individual, capacitaciones, etc.)',
    isSensitive: false,
  },
  {
    code: 'surveillance.certifications.read',
    module: 'surveillance',
    resource: 'certifications',
    action: 'read',
    description: 'Leer credenciales y certificaciones de guardias',
    isSensitive: false,
  },
  {
    code: 'surveillance.contractors.read',
    module: 'surveillance',
    resource: 'contractors',
    action: 'read',
    description: 'Leer compliance corporativo (OS-10, seguros, autorización personal armado)',
    isSensitive: false,
  },
  {
    code: 'surveillance.contractors.update',
    module: 'surveillance',
    resource: 'contractors',
    action: 'update',
    description: 'Actualizar compliance corporativo del contratista',
    isSensitive: true,
  },
  {
    code: 'surveillance.critical_events.create',
    module: 'surveillance',
    resource: 'critical_events',
    action: 'create',
    description: 'Reportar evento crítico (disparo, uso de fuerza, etc.)',
    isSensitive: false,
  },
  {
    code: 'surveillance.critical_events.notify',
    module: 'surveillance',
    resource: 'critical_events',
    action: 'notify',
    description: 'Registrar notificación a Carabineros / Fiscalía / OS-10',
    isSensitive: true,
  },
  {
    code: 'surveillance.critical_events.read',
    module: 'surveillance',
    resource: 'critical_events',
    action: 'read',
    description: 'Leer eventos críticos',
    isSensitive: false,
  },
  {
    code: 'surveillance.critical_events.suspend',
    module: 'surveillance',
    resource: 'critical_events',
    action: 'suspend',
    description: 'Aplicar suspensión preventiva al guardia',
    isSensitive: true,
  },
  {
    code: 'surveillance.critical_events.update',
    module: 'surveillance',
    resource: 'critical_events',
    action: 'update',
    description: 'Actualizar evento crítico (notificaciones, suspensión)',
    isSensitive: false,
  },
  {
    code: 'surveillance.findings.create',
    module: 'surveillance',
    resource: 'findings',
    action: 'create',
    description: 'Registrar nuevo hallazgo en auditoría en curso',
    isSensitive: false,
  },
  {
    code: 'surveillance.findings.read',
    module: 'surveillance',
    resource: 'findings',
    action: 'read',
    description: 'Leer hallazgos de auditoría',
    isSensitive: false,
  },
  {
    code: 'surveillance.findings.resolve',
    module: 'surveillance',
    resource: 'findings',
    action: 'resolve',
    description: 'Marcar hallazgo como resuelto / aceptado',
    isSensitive: false,
  },
  {
    code: 'surveillance.findings.update',
    module: 'surveillance',
    resource: 'findings',
    action: 'update',
    description: 'Actualizar hallazgo (severidad, recomendación, plazo)',
    isSensitive: false,
  },
  {
    code: 'surveillance.guards.create',
    module: 'surveillance',
    resource: 'guards',
    action: 'create',
    description: 'Registrar nuevo guardia/vigilante',
    isSensitive: false,
  },
  {
    code: 'surveillance.guards.read',
    module: 'surveillance',
    resource: 'guards',
    action: 'read',
    description: 'Leer personal de seguridad',
    isSensitive: false,
  },
  {
    code: 'surveillance.guards.terminate',
    module: 'surveillance',
    resource: 'guards',
    action: 'terminate',
    description: 'Dar de baja a un guardia (termination_date + reason)',
    isSensitive: true,
  },
  {
    code: 'surveillance.guards.update',
    module: 'surveillance',
    resource: 'guards',
    action: 'update',
    description: 'Actualizar datos del guardia (categoría, credencial interna, notas)',
    isSensitive: false,
  },
  {
    code: 'surveillance.patrols.end',
    module: 'surveillance',
    resource: 'patrols',
    action: 'end',
    description: 'Cerrar rondín',
    isSensitive: false,
  },
  {
    code: 'surveillance.patrols.read',
    module: 'surveillance',
    resource: 'patrols',
    action: 'read',
    description: 'Leer rondines y trayectos',
    isSensitive: false,
  },
  {
    code: 'surveillance.patrols.start',
    module: 'surveillance',
    resource: 'patrols',
    action: 'start',
    description: 'Iniciar rondín dentro del turno',
    isSensitive: false,
  },
  {
    code: 'surveillance.patrols.upload_track',
    module: 'surveillance',
    resource: 'patrols',
    action: 'upload_track',
    description: 'Enviar breadcrumb GPS (mobile)',
    isSensitive: false,
  },
  {
    code: 'surveillance.shift_reports.lock',
    module: 'surveillance',
    resource: 'shift_reports',
    action: 'lock',
    description: 'Firmar y cerrar parte diario (acción irreversible)',
    isSensitive: true,
  },
  {
    code: 'surveillance.shift_reports.read',
    module: 'surveillance',
    resource: 'shift_reports',
    action: 'read',
    description: 'Leer parte diario',
    isSensitive: false,
  },
  {
    code: 'surveillance.shift_reports.submit',
    module: 'surveillance',
    resource: 'shift_reports',
    action: 'submit',
    description: 'Redactar y enviar parte diario',
    isSensitive: false,
  },
  {
    code: 'surveillance.shifts.cancel',
    module: 'surveillance',
    resource: 'shifts',
    action: 'cancel',
    description: 'Cancelar turno antes de iniciar',
    isSensitive: false,
  },
  {
    code: 'surveillance.shifts.end',
    module: 'surveillance',
    resource: 'shifts',
    action: 'end',
    description: 'Cerrar turno (in_progress→completed o no_show)',
    isSensitive: false,
  },
  {
    code: 'surveillance.shifts.read',
    module: 'surveillance',
    resource: 'shifts',
    action: 'read',
    description: 'Leer turnos planificados y ejecutados',
    isSensitive: false,
  },
  {
    code: 'surveillance.shifts.schedule',
    module: 'surveillance',
    resource: 'shifts',
    action: 'schedule',
    description: 'Planificar turno (status=scheduled)',
    isSensitive: false,
  },
  {
    code: 'surveillance.shifts.start',
    module: 'surveillance',
    resource: 'shifts',
    action: 'start',
    description: 'Iniciar turno (scheduled→in_progress)',
    isSensitive: false,
  },

  // users
  {
    code: 'users.users.manage',
    module: 'users',
    resource: 'users',
    action: 'manage',
    description: 'Gestionar usuarios',
    isSensitive: false,
  },
  {
    code: 'users.users.reset_mfa',
    module: 'users',
    resource: 'users',
    action: 'reset_mfa',
    description: 'Resetear MFA de un usuario (auditado)',
    isSensitive: true,
  },

  // vehicles
  {
    code: 'vehicles.associations.create',
    module: 'vehicles',
    resource: 'associations',
    action: 'create',
    description: 'Registrar nueva asociación',
    isSensitive: false,
  },
  {
    code: 'vehicles.associations.end',
    module: 'vehicles',
    resource: 'associations',
    action: 'end',
    description: 'Cerrar asociación (valid_to)',
    isSensitive: false,
  },
  {
    code: 'vehicles.associations.read',
    module: 'vehicles',
    resource: 'associations',
    action: 'read',
    description: 'Leer asociaciones party↔vehicle',
    isSensitive: true,
  },
  {
    code: 'vehicles.associations.update',
    module: 'vehicles',
    resource: 'associations',
    action: 'update',
    description: 'Actualizar asociación (notas, confidence)',
    isSensitive: false,
  },
  {
    code: 'vehicles.documents.delete',
    module: 'vehicles',
    resource: 'documents',
    action: 'delete',
    description: 'Marcar documento como eliminado (soft delete)',
    isSensitive: true,
  },
  {
    code: 'vehicles.documents.download',
    module: 'vehicles',
    resource: 'documents',
    action: 'download',
    description: 'Descargar documento (acción auditada)',
    isSensitive: true,
  },
  {
    code: 'vehicles.documents.read',
    module: 'vehicles',
    resource: 'documents',
    action: 'read',
    description: 'Leer metadata de documentos del vehículo',
    isSensitive: false,
  },
  {
    code: 'vehicles.documents.update',
    module: 'vehicles',
    resource: 'documents',
    action: 'update',
    description: 'Actualizar metadata del documento (no contenido)',
    isSensitive: false,
  },
  {
    code: 'vehicles.documents.upload',
    module: 'vehicles',
    resource: 'documents',
    action: 'upload',
    description: 'Subir nuevo documento al vehículo',
    isSensitive: false,
  },
  {
    code: 'vehicles.sightings.create',
    module: 'vehicles',
    resource: 'sightings',
    action: 'create',
    description: 'Registrar nuevo avistamiento',
    isSensitive: false,
  },
  {
    code: 'vehicles.sightings.delete',
    module: 'vehicles',
    resource: 'sightings',
    action: 'delete',
    description: 'Marcar avistamiento como eliminado (soft delete)',
    isSensitive: true,
  },
  {
    code: 'vehicles.sightings.read',
    module: 'vehicles',
    resource: 'sightings',
    action: 'read',
    description: 'Leer avistamientos del vehículo',
    isSensitive: false,
  },
  {
    code: 'vehicles.sightings.update',
    module: 'vehicles',
    resource: 'sightings',
    action: 'update',
    description: 'Actualizar metadata del avistamiento',
    isSensitive: false,
  },
  {
    code: 'vehicles.vehicles.create',
    module: 'vehicles',
    resource: 'vehicles',
    action: 'create',
    description: 'Crear vehículos',
    isSensitive: false,
  },
  {
    code: 'vehicles.vehicles.read',
    module: 'vehicles',
    resource: 'vehicles',
    action: 'read',
    description: 'Leer vehículos',
    isSensitive: false,
  },
  {
    code: 'vehicles.vehicles.update',
    module: 'vehicles',
    resource: 'vehicles',
    action: 'update',
    description: 'Actualizar vehículos',
    isSensitive: false,
  },
];

// Validación estática del catálogo (se ejecuta al importar el módulo).
// Detecta duplicados antes de que arranque la app.
(() => {
  const seen = new Set<string>();
  for (const p of PERMISSIONS_CATALOG) {
    if (seen.has(p.code)) {
      throw new Error(`PERMISSIONS_CATALOG: code duplicado '${p.code}'`);
    }
    seen.add(p.code);
    const expected = `${p.module}.${p.resource}.${p.action}`;
    if (p.code !== expected) {
      throw new Error(
        `PERMISSIONS_CATALOG: code '${p.code}' no coincide con module.resource.action='${expected}'`,
      );
    }
  }
})();
